### ISSUE TITLE
Count keep increment on mousedown and move away from the spinner button

### ISSUE THREAD

**Issue by yogesh-kumawat** [wajdibeltaifa/ng-number-picker#7]
If we mousedown on the number spinner buttons and drag the mouse with press state (don't let it fire mouseup event) outside of the spinner then it keep increment/decrement the number.

![image](https://user-images.githubusercontent.com/42549838/87392580-66623800-c5ca-11ea-8c7e-422e9e922cff.png)

How we can stop increment/decrement value inside the component when mouse is not on spinner buttons.

**Comment by Amitesh** [comment]
Hi Yogesh,

You can listen the `mouseout/mouseleave` event and call the `mouseUp` callbacks which will clear the timer that is set inside the library to increment the count value on long mouse press. 

```javascript
ngAfterViewInit() {
  this.upButton=this.elRef.nativeElement.querySelectorAll('.up')[0];
  this.downButton=this.elRef.nativeElement.querySelectorAll('.down')[0];

  this.renderer.listen(this.upButton, 'mouseleave', ($event: any) => {
     console.log('onmouseleave', $event);
     let mouseUpEvent: Event = new MouseEvent('mouseup');
     this.upButton.dispatchEvent(mouseUpEvent);
 });

 this.renderer.listen(this.downButton, 'mouseleave', ($event: any) => {
     console.log('onmouseleave', $event);
     let mouseUpEvent: Event = new MouseEvent('mouseup');
     this.downButton.dispatchEvent(mouseUpEvent);
 });
}
```

I hope, it will help you.

**Comment by yogesh-kumawat** [comment]
Thanks for the suggestions. It worked like a charm. Thanks.

**Comment by Amitesh** [comment]
AWESOME!!
